# Site settings
title: Samuel Ivan Gunadi
description: A Resume Site
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Samuel Ivan Gunadi
user_description: This is me.
user_title: Software Engineer
email: algscientist@gmail.com
# twitter_username: lorem_ipsum
github_username:  multiprecision
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
